import Foundation

/// Re-derives the exact `signingPayload` bytes (security-broker-contract §8.2)
/// from a challenge's discrete fields — a **faithful port** of the broker's
/// `buildSigningPayload` + `effectCommitmentLines`
/// (`packages/broker/src/authorize.ts`). This is the signer's independent
/// backstop: `sign` re-derives and refuses (exit 2) if the result disagrees with
/// the challenge's own `signingPayload`, so the bytes it signs are provably the
/// bytes it displayed. Cross-implementation byte-identity is pinned by the
/// committed golden vectors in `Tests/.../Fixtures` (generated by the broker).
public enum SigningPayload {
    static let prefix = "atlas.authz.v1"

    /// Re-derive the payload; throws `SignerError(.malformedChallenge)` on a
    /// missing/mistyped effect field or an embedded line separator (which would
    /// make the newline framing ambiguous — the same injective check the broker
    /// enforces at mint + verify).
    public static func rederive(from c: AuthorizationChallenge) throws -> String {
        var lines: [String] = [
            prefix,
            c.op,
            c.runId ?? "-",
            c.targetCommit ?? "-",
            c.canonicalBaseCommit,
            c.nonce,
        ]
        lines.append(contentsOf: try commitmentLines(c.intendedEffect))
        for line in lines where line.contains("\n") || line.contains("\r") {
            throw SignerError(.malformedChallenge, "authorization field contains an embedded line separator")
        }
        return lines.joined(separator: "\n")
    }

    /// The op-specific commitment lines appended after the six-line preamble —
    /// identical ordering + formatting to the broker's `effectCommitmentLines`.
    private static func commitmentLines(_ effect: [String: JSONValue]) throws -> [String] {
        guard let kind = effect["kind"]?.asString else {
            throw SignerError(.malformedChallenge, "intendedEffect.kind is missing or not a string")
        }
        func str(_ key: String) throws -> String {
            guard let v = effect[key]?.asString else {
                throw SignerError(.malformedChallenge, "intendedEffect.\(key) is missing or not a string")
            }
            return v
        }
        func intStr(_ key: String) throws -> String {
            guard let v = effect[key]?.asInt else {
                throw SignerError(.malformedChallenge, "intendedEffect.\(key) is missing or not an integer")
            }
            return String(v)
        }
        switch kind {
        case "integrate": return [try intStr("tier"), try str("changePlanDigest")]
        case "revert": return [try str("revertCommit")]
        case "erase": return [try str("oldHead"), try str("replacementHead"), try str("scope")]
        case "restore": return [try str("backupRef"), try str("backupContentHash")]
        case "graduate": return [try intStr("fromGeneration"), try intStr("toGeneration"), try str("migrationPlanDigest")]
        case "trust": return [try str("sourceOpaqueId"), try str("fromLevel"), try str("toLevel")]
        case "forceUnblock": return [try intStr("latestLedgerSeq"), try intStr("acceptedRpoGap")]
        case "quarantineInspect": return [try str("quarantineItemOpaqueId")]
        case "quarantineResolve": return [try str("quarantineItemOpaqueId"), try str("resolution")]
        default:
            throw SignerError(.malformedChallenge, "unknown intendedEffect.kind \"\(kind)\"")
        }
    }
}
